# Generated by Django 5.2.8 on 2025-11-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_artes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rolname',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OPERADOR', 'Operador'), ('ARTISTA', 'Artista')], default='OPERADOR', max_length=20),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
