# Generated by Django 5.2.8 on 2025-11-12 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_artes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboraciones',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistas_colab', to='gestor_artes.artistas'),
        ),
    ]
