# Generated by Django 5.2.8 on 2025-11-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_artes', '0002_alter_colaboraciones_artista'),
        ('gestor_artes', '0002_alter_usuario_rolname_delete_rol'),
    ]

    operations = [
    ]
