# Generated by Django 5.2.8 on 2025-11-12 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_artes', '0003_merge_20251112_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_historial', models.TextField(max_length=200)),
                ('tabla_afectada_historial', models.TextField(max_length=100)),
                ('fecha_hora_historial', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_artes.usuario')),
            ],
        ),
    ]
